name: basic_http_server
author: Seth Ladd <sethladd@gmail.com>
version: 0.0.1
homepage: https://github.com/igrigorik/heroku-buildpack-dart
description: A minimal static HTTP server to demonstrate Dart on Heroku.
dependencies:
  browser: any
  shelf: any
  shelf_static: any
